### ISSUE TITLE
Memory leak in WiFiManager from Android SDK

### ISSUE THREAD

**Issue by johnwatsondev** [pwittchen/NetworkEvents#106]
* Instantiation of `WifiManager` should use `Application` level Context instead of `Activity` level in [`NetworkEvents.java`](https://github.com/pwittchen/NetworkEvents/blob/master/network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkEvents.java). Otherwise it will occur leak in `WifiManager`. The reference tree was attached below from [leakcanary](https://github.com/square/leakcanary). This leak was reported in [Issue 43945](https://code.google.com/p/android/issues/detail?id=43945) from android issues.

```
GC ROOT com.android.internal.util.AsyncChannel$DeathMonitor.this$0
references com.android.internal.util.AsyncChannel.mSrcContext
leaks com.test.demo.SplashActivity instance
```

Fix code in [`NetworkEvents.java`](https://github.com/pwittchen/NetworkEvents/blob/master/network-events-library/src/main/java/com/github/pwittchen/networkevents/library/NetworkEvents.java):
```diff
public void register() {
    registerNetworkConnectionChangeReceiver();
    registerInternetConnectionChangeReceiver();

    if (wifiAccessPointsScanEnabled) {
      registerWifiSignalStrengthChangeReceiver();
      // start WiFi scan in order to refresh access point list
      // if this won't be called WifiSignalStrengthChanged may never occur
-     WifiManager wifiManager = (WifiManager) context.getSystemService(Context.WIFI_SERVICE);
+     WifiManager wifiManager = (WifiManager) context.getApplicationContext().getSystemService(Context.WIFI_SERVICE);
      wifiManager.startScan();
    }
  }
```
---
* `ConnectivityManager` can also leak `Activity`.

leakcanary dump heap info:  
```
//GC ROOT static android.net.ConnectivityManager.sInstance
//references android.net.ConnectivityManager.mContext
//leaks com.test.demo.SplashActivity instance
```

Fix code in [`NetworkConnectionChangeReceiver `](https://github.com/pwittchen/NetworkEvents/blob/master/network-events-library/src/main/java/com/github/pwittchen/networkevents/library/receiver/NetworkConnectionChangeReceiver.java):  
```diff
  private ConnectivityStatus getConnectivityStatus(Context context) {
-   ConnectivityManager connectivityManager = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
+   ConnectivityManager connectivityManager = (ConnectivityManager) context.getApplicationContext().getSystemService(Context.CONNECTIVITY_SERVICE);
    NetworkInfo networkInfo = connectivityManager.getActiveNetworkInfo();

    if (networkInfo != null) {
      if (networkInfo.getType() == ConnectivityManager.TYPE_WIFI) {
        return ConnectivityStatus.WIFI_CONNECTED;
      } else if (networkInfo.getType() == ConnectivityManager.TYPE_MOBILE) {
        return ConnectivityStatus.MOBILE_CONNECTED;
      }
    }

    return ConnectivityStatus.OFFLINE;
  }
```
---
* There was an odd behave about those leaks. Because `WifiManager` and `ConnectivityManager` were created in so many different places in your codebase. Why just has these two places leak? 

Looking forward to your reply. Thanks in advance. :)

**Comment by pwittchen** [comment]
Thank you for your work and investigating this issue!

As you can see, constructor of NetworkEvents class accepts Context as a parameter, so you can pass Application Context instead of Activity context inside your app. There's no need to update library.

I'll take a closer look at it later and read note on Google issue tracker carefully to analyze this problem better.

Nevertheless, we can update sample apps in the repository as well as documentation and add appropriate note about this issue.

**Comment by johnwatsondev** [comment]
Yep, you got it.  
Some idea about the strategy about this library's implement. It will be more efficient if `NetworkEvents` initialize in Application with a callback notice registered Activity or Fragment. How about this idea?

**Comment by pwittchen** [comment]
I've updated code samples and added recommendation note in `README.md` file in [Initialize objects](https://github.com/pwittchen/NetworkEvents#initialize-objects) section.

I hope this bug will be fixed in the next Android releases.

I think this issue can be closed for now.
