### ISSUE TITLE
isConnectedToAnyNetwork

### ISSUE THREAD

**Issue by Shargotth** [pwittchen/NetworkEvents#109]
Hi,

It seems that a class called "NetworkHelper" existed in previous versions with a method "isConnectedToAnyNetwork" but now that this class has been removed I can't see where this method has been added or replaced, could someone help me?

Thank you !

**Comment by pwittchen** [comment]
Hi,

I removed this method, because it was no longer used internally by the library and approach was changed a bit. Do you find useful? If yes, we can add it back.

**Comment by Shargotth** [comment]
I'm maybe wrong but I think it could be useful in the case you want to know if the device got an internet connection before the first "connection event" is thrown and capture by the EventBus (I'm using NetworkEvent with otto-bus like in the exemple).

**Comment by pwittchen** [comment]
Yeah, maybe in case of event bus it would be useful as you say. I'm gonna add this feature back. Probably, I'll use different and more descriptive class name than `NetworkHelper`. I'll notify you about update in this issue.

**Comment by Shargotth** [comment]
Great ! Thank you for the quick answer and for this nice library !

**Comment by pwittchen** [comment]
I've added back `NetworkHelper` class with single static method called `isConnectedToWiFiOrMobileNetwork(context)`. It will be available in the next release.
