### ISSUE TITLE
OnlineCheckerImpl does not check for internet connectivity

### ISSUE THREAD

**Issue by lingz** [pwittchen/NetworkEvents#111]
The OnlineCheckerImpl only checks if there is a network connection available (packets can be sent) but not whether it is connected to the greater internet.

As described in this stackoverflow:
http://stackoverflow.com/questions/6493517/detect-if-android-device-has-internet-connection

A decent way to do this would be checking if a host is reachable with a small timeout at a regular interval:
http://stackoverflow.com/questions/8919083/checking-host-reachability-availability-in-android

**Comment by pwittchen** [comment]
Probably, you're right. In previous versions of the library I was performing actual ping, but it seemed to be not so reliable. Moreover, I wasn't sure which solution is the best and actually correct. Nevertheless if people encountering problems with that or false-positive information, it would be good to update it. I think, we can combine existing solution (checking available network connection and if we can send packets) with actual ping. I think this solution looks good: http://stackoverflow.com/a/25816086/1150795. What do you think? We can also make this url configurable, but when given host will be unavailable, final result will be wrong.

**Comment by lingz** [comment]
I'm doing actual pings in my app. I wrote this answer:

http://stackoverflow.com/a/35647892/1820510

The only difference is that instead of sending a full TCP request, I just check establish the TCP connection and then close the socket right after so its a bit faster to execute.

**Comment by pwittchen** [comment]
It seems to be reasonable. I'll check it out and probably enhance existing solution. Optionally, if you want to contribute to this project, good PRs are welcome. :)

**Comment by pwittchen** [comment]
I'm wondering if opening a TCP connection requires running such operation in a separate thread asynchronously like regular HTTP request. I guess it may be necessary.

**Comment by lingz** [comment]
Yup you need to do it in a background thread, android will actually throw an exception if you do networking on the main thread. I'm using a scheduler like this:

https://github.com/lingz/NetworkMonitor/blob/master/android/app/src/main/java/com/networkmonitor/NetworkMonitoringService.java#L150

**Comment by pwittchen** [comment]
It's fixed. Now, we're pinging remote host. Update will be available in the next release.
