### ISSUE TITLE
Returning WIFI_CONNECTED_HAS_INTERNET when no connection

### ISSUE THREAD

**Issue by joielechong** [pwittchen/NetworkEvents#112]
I'm using code from [example-greenrobot-bus](https://github.com/pwittchen/NetworkEvents/tree/master/example-greenrobot-bus). It always return WIFI_CONNECTED_HAS_INTERNET though my device only connected to ad-hoc WiFi. 

Maybe this related with #111 issue.

**Comment by pwittchen** [comment]
Thanks for reporting this issue. I'll check it out.

**Comment by pwittchen** [comment]
It's fixed. Now, we're pinging remote host. Update will be available in the next release.
