### ISSUE TITLE
Missing @Subscribe event annotation in green robot example

### ISSUE THREAD

**Issue by suclike** [pwittchen/NetworkEvents#113]
$subj

**Comment by pwittchen** [comment]
My example is for GreenRobot EventBus 2.4.1. As far as I remember that version does not support "Subscribe" annotations and this event bus works without them, so this example is valid. I didn't follow latest changes in this bus, but I see they introduced annotations. PR-s with upgraded version of GreenRobot event bus in example are welcome.

**Comment by suclike** [comment]
Yeah, sorry, I didn't check what lib version you're using. PR created with update GreenRobot lib version.

**Comment by pwittchen** [comment]
Okay, thanks. I'll review it soon. :)

**Comment by pwittchen** [comment]
Solved by #114.
