### ISSUE TITLE
Is there any plan for support older android versions?

### ISSUE THREAD

**Issue by nekofar** [pwittchen/NetworkEvents#13]
As I noticed this library only available for API level 15 and above. Is there any plan for support older android versions?

**Comment by pwittchen** [comment]
I can check, if it's possible to add backward compatibility. Which from API do you want to support your application?

**Comment by nekofar** [comment]
Must of my customers still using old devices and I usually use min SDK 9 or 10 and also android support libraries.

**Comment by pwittchen** [comment]
Support for min SDK 9 will be available in version 1.0.1 of the library.

**Comment by nekofar** [comment]
Thank you. 👍

**Comment by pwittchen** [comment]
Done. Version 1.0.1 is now available on Maven Central Repository.
