### ISSUE TITLE
Add new values to ConnectivityStatus

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/NetworkEvents#28]
Add new network states:
- `WIFI_CONNECTING("connecting to WiFi network...")`
- `WIFI_DISCONNECTED("disconnected from WiFi network")`
- `MOBILE_CONNECTING("connecting to mobile network...")`
- `MOBILE_DISCONNECTED("disconnected from mobile network")`

References:
- http://developer.android.com/reference/android/net/NetworkInfo.State.html
- http://stackoverflow.com/questions/3841317/how-to-see-if-wifi-is-connected-in-android

**Comment by johnwatson5412** [comment]
Thx for enhancement this feature!!!  :dancer:

**Comment by pwittchen** [comment]
It wasn't added yet, but I'm planning to add this in the new version of the library if there won't be any problems with that.

**Comment by pwittchen** [comment]
I had some problems with implementing this feature. Probably, it needs to be implemented in a different way (maybe without broadcast receivers?) in order to achieve that feature. Currently, I am closing it.
If anyone would like to implement that, I can re-open this issue or accept PR with properly working code.
