### ISSUE TITLE
Create unit tests for broadcast receivers

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/NetworkEvents#30]
Testing connectivity status with unit tests is not so obvious task in Android and needs some investigation. Write unit tests for broadcast receivers, which force changes of connectivity status and  check whether proper events were pushed to the bus after receiving an Intent.

**Comment by johnwatson5412** [comment]
Did this feature has released?

**Comment by pwittchen** [comment]
It **wasn't released** yet (issue is currently open), but I'm planning to add unit tests in the new version of the library if there won't be any problems with that. I see that other people had problems with testing connectivity on android, so it's gonna be quite experimental.
