### ISSUE TITLE
Create GitHub release of version 1.0.5

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/NetworkEvents#52]

**Comment by YuriHeupa** [comment]
Is there any release date for this version?

**Comment by pwittchen** [comment]
There isn't any specific date of release, but I'm going to upload archives with new version today or tomorrow. After upload, we will have to wait for Maven Sync. I think, new version will be available tomorrow on 13th of May or on 14th of May. Please, watch this repository to be updated.

**Comment by pwittchen** [comment]
Version 1.0.5 was released.
