### ISSUE TITLE
Add abstraction, which will allow to add any event bus implementation

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/NetworkEvents#57]
I need an interface, which will look like that:
```java
interface EventPublisher {
   void post(Object event);
}
```

I also need to add possibility to set implementation of this interface in `NetworkEvents` object via second constructor. This feature should be optional. I can leave Otto event bus as a default implementation, when user hasn't defined his own bus implementation. Moreover, I can add some example with a different event bus (e.g. https://github.com/greenrobot/EventBus as it's quite popular).

**Comment by mseroczynski** [comment]
+1, as you may know Otto isn't compatible with Android Annotations which is also quite popular (at least for me it was main reason to start using GreenRobot's bus).

**Comment by pwittchen** [comment]
@mseroczynski Thank you for your message. I know Android Annotations project, but currently I don't use it on daily basis. I've noticed that some people may want to use NetworkEvents with a different bus than Otto (like GreenRobot's) or custom bus implementation, so I am going to add such update in the nearest days.

**Comment by kamilwlf** [comment]
I also use greenrobot/EventBus, because it is more popular

**Comment by pwittchen** [comment]
I've added this feature to the next milestone.

**Comment by pwittchen** [comment]
I've added `BusWrapper` interface, which loooks like this:
```java
public interface BusWrapper {
    void register(Object object);
    void unregister(Object object);
    void post(Object event);
}
```

Now, `NetworkEvents` accepts `BusWrapper` instead of Otto Bus object and any event bus can implement it.

**Comment by pwittchen** [comment]
It's done. Update is available on the repo and will be available in the next release.
I only need to update docs in `README.md`.
