### ISSUE TITLE
Toggle logging on/off

### ISSUE THREAD

**Issue by RadicalMonkey** [pwittchen/NetworkEvents#58]
Is this possible? I find that my logs are saturated with messages about ```WifiSignalStrengthChanged```.

**Comment by pwittchen** [comment]
Thanks for asking the question.

Currently, you can turn off wifi scanning. Please, take a look here: https://github.com/pwittchen/NetworkEvents#initialize-objects

If you compile the app in release mode, it should not produce any logs.
Toggling logs is good idea, so I can add it to the next version of the library.

**Comment by RadicalMonkey** [comment]
I've turned off wifi scanning and that's solved it for the time being. Having the toggling function would be great, thanks!

**Comment by pwittchen** [comment]
If you don't need to perform any action when Wifi signal strength is changing, you should have Wifi scanning turned off. Nevertheless, I'm going to add possibility to turn off logs.

**Comment by pwittchen** [comment]
Now, we can disable logging by passing EmptyLogger implementation as follows:

```java
new NetworkEvents(context, bus, new EmptyLogger());
```

I know, it's not the best solution, but in current version of the library implementation of the logger have to be passed during object creation. We can think of improving it in the future.

This functionality is not available on Maven Central yet. It will be available in the next release.
