### ISSUE TITLE
Periodically ping (polling) the server

### ISSUE THREAD

**Issue by kamilwlf** [pwittchen/NetworkEvents#61]
Not only at startup, but during the application? for example after 10 minutes we lose the connection to the Internet but WIFI is connected(connected is a WiFi (internet not available)).

Is the library is able to detect that situation?
Is polls the server at intervals of time?

**Comment by pwittchen** [comment]
Library is not currently polling the remote server. It only detects connectivity status change (connected to WiFi, connected mobile or offline). It pings the server only when status is changed from offline to connected.

Library currently does not support situation described by you. I think, it's a good idea for the new feature and we can add possibility to enable polling when user is connected to mobile or WiFi network.

**Comment by kamilwlf** [comment]
add possibility to enable polling when user is connected to mobile or WiFi network and save result to permanent memory(e.q db or SharedPreferences).

I would like to get this result:
NetworkHelper.getConnectivityStatusResult()

Timestamp dateOfLastPull;//to know when was the last ping

pseudo code:
http://paste.ofcode.org/G4taG8R9iT7LeLmbsPT5BP

**Comment by pwittchen** [comment]
Currently, I disabled ping method, because it was not reliable and in most cases it wasn't useful.
For periodical ping (polling) I recommend using RxJava. You can take a look at this article: http://blog.freeside.co/2015/01/29/simple-background-polling-with-rxjava/ . It's quite good and stable solution.
