### ISSUE TITLE
Discuss about OnlineCheckerImpl 's isOnline(context) method

### ISSUE THREAD

**Issue by johnwatsondev** [pwittchen/NetworkEvents#83]
Why use [isConnectedOrConnecting()](http://developer.android.com/reference/android/net/NetworkInfo.html#isConnectedOrConnecting()) rather than [isConnected()](http://developer.android.com/reference/android/net/NetworkInfo.html#isConnected()) ?

For isConnectedOrConnecting method's javadoc:
Indicates whether network connectivity exists or is in the process of being established. This is good for applications that need to do anything related to the network other than read or write data. For the latter, call isConnected() instead, which **guarantees** that the network is **fully usable**.

Thanks for refactor code again and i have used this nice library in my productive project.
Thanks in advance!

**Comment by pwittchen** [comment]
You're right. I think, we can replace `isConnectedOrConnecting()` with `isConnected()`. We just need to test whether it behaves correctly.

**Comment by pwittchen** [comment]
I've updated it in https://github.com/pwittchen/NetworkEvents/commit/cf58d70233c7174aedde50828822e74a158b22e3. Update will be available in the next release.

**Comment by johnwatsondev** [comment]
I appreciate you hard work!  Thanks again!@pwittchen

**Comment by pwittchen** [comment]
Please remember that Internet connection checking functionality is disabled by default in the newest version of the library. If you want to use it, you need to enable it. It is described here: https://github.com/pwittchen/NetworkEvents#enabling-internet-connection-check

**Comment by johnwatsondev** [comment]
Yes! I have read your guide. 
I will be test and try find bugs in my productive project.
