### ISSUE TITLE
it's better to support maven repo too

### ISSUE THREAD

**Issue by wangbourne** [pwittchen/NetworkEvents#9]
Currently, I have to include it as an Android Library, rather than a simple command like "compile 'com.github.pwittchen.networkevents:2.4.0+'"

**Comment by pwittchen** [comment]
Hello!
First of all, thank you for being interested in this project. I'm actually started preparing for release process in issue #6 and NetworkEvents library will be available in Maven Central Repository. It means that you will be able to add it as Gradle or Maven dependency very soon. Maybe even today. I will inform you about the update in this issue.

**Comment by pwittchen** [comment]
Done. Download section was added to the README.md file.
